services:
  archive:
    image: docker.io/library/ruby:alpine
    depends_on:
      firefox:
        condition: service_healthy
    command: >-
      sh -c "
      ./archive-mailchimp-invoice.rb
      "
    working_dir: /app
    env_file: .env
    environment:
      WEBDRIVER_BROWSER: firefox
      WEBDRIVER_HEADLESS: "true"
      WEBDRIVER_REMOTE_URL: http://firefox:4444/wd/hub
    volumes:
    - type: bind
      source: .
      target: /app

  firefox:
    image: docker.io/selenium/standalone-firefox:4
    environment:
      START_XVFB: "false"
    healthcheck:
      test:
      - "CMD"
      - "/opt/bin/check-grid.sh"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "4444"
      interval: 10s
      timeout: 10s
      retries: 9
